### ISSUE TITLE
Future of the controller

### ISSUE THREAD

**Issue by gitbluf** [phoban01/cue-flux-controller#3]
Hello!

Wanted to ask what is the future of the controller?

Cheers

**Comment by phoban01** [comment]
Hey @gitbluf 👋🏻 

There may be more work done if folks find it useful. 

Do you have use cases you could share?

I am interested to see how cue's module system develops as this will be relevant to how the controller might evolve.

Happy to hear feedback and thoughts!

kind regrads

**Comment by gitbluf** [comment]
@phoban01 Sorry for late reply I somehow totally missed your response.
So my current case is that my team(platform sre) maintains K8s definitions and just exposes api that is used control what gets created. Afterwards it gets generate, packaged as OCI and pushed, then pulled and deployed by Kustomize-controller that references the OCI repo.
Now, what I'm looking into is something that can deploy CUE files(built/apply) and provide input for build dynamically(example, commit-sha, branch-name etc)

Cheers

**Comment by onedr0p** [comment]
@gitbluf this issue might share some insight https://github.com/stefanprodan/timoni/issues/10

**Comment by gitbluf** [comment]
@onedr0p Thanks for letting me know!
